version: '3'
services:
  mysql:
    build: ./mysql
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kevin#1986
      - MYSQL_PASSWORD=admin#1999
      - MYSQL_USER=admin
      - MYSQL_DATABASE=blog_db
  blog:
    depends_on:
      - mysql
    build: ./blog
    image: blog
    container_name: blog
    ports:
      - 8080:8080
    links:
      - mysql
  nginx:
    #build: ./nginx
    image: daocloud.io/library/nginx
    container_name: nginx
    ports:
      - 80:80